export const translations = {
  en: {
    SingIn: "Sign In",
    SingInText: "Sign In",
    SingUp: "Sign Up",
    Language: "Language",
    ChooseLanguage: "English",
    Logout: "Logout",
    DarkMode: "Dark Mode",
    Chats: "Chats",
    FirstMessage: "Say Hi 👋",
    ForgotPassword: "Forgot password?",
    HaveAccount: "Don`t have an account?",
    AlreadyHaveAccount: "Already have an account?",
  },
  ua: {
    SingIn: "Увійти",
    SingInText: "Вхід",
    SingUp: "Зареєструватися",
    Language: "Мова",
    ChooseLanguage: "Українська",
    Logout: "Вийти",
    DarkMode: "Нічний режим",
    Chats: "Чати",
    FirstMessage: "Вітання 👋",
    ForgotPassword: "Забули пароль?",
    HaveAccount: "Не маєте акаунту?",
    AlreadyHaveAccount: "Вже маєте акаунт?",
  },
};
